apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 1 # delay starting analysis run until setWeight: 40%
        args:
          - name: namespace
            value: default
          - name: rollout-name
            value: rollouts-demo
          - name: canary-pod-hash
            valueFrom:
              podTemplateHashValue: Latest
      trafficRouting:
        istio:
          virtualServices:
            - name: rollouts-demo
              routes:
                - primary
          destinationRule:
            name: rollout-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: 5
        - pause: { duration: 30s }
        - setWeight: 15
        - pause: { duration: 30s }
        - setWeight: 30
        - pause: { duration: 30s }
        - setWeight: 60
        - pause: { duration: 30s }
        - setWeight: 80
        - pause: { duration: 30s }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
        istio-injection: enabled
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
