apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        # startingStep: 2 # delay starting analysis run until setWeight: 40%
        args:
          - name: service-name
            value: rollouts-demo-canary.default.svc.cluster.local
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        istio:
          virtualServices:
            - name: rollouts-demo # At least one virtualService is required
              routes:
                - primary # At least one route is required
      steps:
        - setWeight: 5
        - pause: { duration: 1m }
        - setWeight: 15
        - pause: { duration: 1m }
        - setWeight: 30
        - pause: { duration: 1m }
        - setWeight: 60
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
        istio-injection: enabled
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:red
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
