apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo
spec:
  gateways:
    - istio-system/monitor-gateway
  hosts:
    - "moamoa-news.com"
  http:
    - name: primary
      route:
        - destination:
            host: rollouts-demo-stable
            port:
              number: 80
          weight: 100
        - destination:
            host: rollouts-demo-canary
            port:
              number: 80
          weight: 0
