apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: namespace
    - name: rollout-name
    - name: canary-pod-hash
  metrics:
    - name: success-rate
      interval: 30s
      successCondition: result[0] >= 0.95
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring:9090
          query: |
            sum(irate(
              istio_requests_total{reporter=~"destination",destination_workload_namespace=~"{{args.namespace}}",destination_workload=~"{{args.rollout-name}}-{{args.canary-pod-hash}}",response_code!~"5.*"}[5m]
            )) /
            sum(irate(
              istio_requests_total{reporter=~"destination",destination_workload_namespace=~"{{args.namespace}}",destination_workload=~"{{args.rollout-name}}-{{args.canary-pod-hash}}"}[5m]
            ))
